export const API_ROUTES = (baseUrl: string) => ({
    NEST_LOGIN: `${baseUrl}/auth/login`,
    NEST_USERS: `${baseUrl}/utilisateur`,
    NEST_PRODUITS: `${baseUrl}/produit`,
    NEST_PRODUITS_AVECTYPE: `${baseUrl}/produit/avecType`,
    NEST_TYPE_PRODUITS: `${baseUrl}/type-produit`,
    NEST_PARTICIPATIONS: `${baseUrl}/participation`,
    NEST_CRENEAUX: `${baseUrl}/creneau`,
    NEST_PANIER: `${baseUrl}/panier`,
    NEST_PANIER_COMPLET: `${baseUrl}/panier/complets`,
    NEST_PRODUIT_PANIER: `${baseUrl}/produit-panier`,
    NEST_COMMANDE: `${baseUrl}/commande`,
    NEST_COMMANDE_PRODUIT: `${baseUrl}/commande-produit`,
    NEST_UTILISATEUR_QUOTA: `${baseUrl}/utilisateur/quotas`,
});
